#!groovy
import groovy.json.*
DOCKER_HOST=params['DOCKER_HOST']

REGISTRY="192.168.0.1"
REGISTRY_URL="https://${REGISTRY}/"

DOCKER_CONTAINER=[:]
RELEASE_OUT_DIR="/net/fileserver/"
LOCAL_TAR_DIR="/mnt/workspace/tmp/"
TEST_ARGS = ""
branches = [:]
failures = ""
ADMIN_ACCOUNT = "release-bot@arangodb.com"
parallelJobNames = []
ADMIN_ACCOUNT = "willi@arangodb.com"
lastKnownGitRev = ""
currentGitRev = ""
WORKSPACE = ""
BUILT_FILE = ""
DIST_FILE = ""
BUILD_DIR = ""
fatalError = false
VERBOSE = true

testParams = [:]

@NonCPS
def printParams() {
  env.getEnvironment().each { name, value -> println "Name: $name -> Value $value" }
}

print("blarg")
printParams()
print(env)
testPathPrefix = 'j'
//currentBuild.result = 'SUCCESS'
def CONTAINERS=[
  [ 'buildType': 'docker', 'testType': 'docker', 'name': 'centosix',            'packageFormat': 'RPM',    'OS': "Linux",   'buildArgs': "--rpath --jemalloc --rpmDistro centos", 'cluster': true, 'LOCALFS': '/mnt/workspace/tmp/', 'FS': '/mnt/data/fileserver/', 'reliable': false, 'BUILD': '', 'CBUILD':'', 'SYMSRV':'', 'testArgs': ''],
  [ 'buildType': 'docker', 'testType': 'docker', 'name': 'centoseven',          'packageFormat': 'RPM',    'OS': "Linux",   'buildArgs': "--rpath --jemalloc --rpmDistro centos", 'cluster': true,  'LOCALFS': '/mnt/workspace/tmp/', 'FS': '/mnt/data/fileserver/', 'reliable': true, 'BUILD': '', 'CBUILD':'', 'SYMSRV':'', 'testArgs': ''],
  [ 'buildType': 'docker', 'testType': 'docker', 'name': 'fedoratwentyfive',   'packageFormat': 'RPM',    'OS': "Linux",   'buildArgs': "--rpath --jemalloc --rpmDistro centos", 'cluster': true,  'LOCALFS': '/mnt/workspace/tmp/', 'FS': '/mnt/data/fileserver/', 'reliable': true, 'BUILD': '', 'CBUILD':'', 'SYMSRV':'', 'testArgs': ''],
  [ 'buildType': 'docker', 'testType': 'docker', 'name': 'opensusefortytwo',    'packageFormat': 'RPM',    'OS': "Linux",   'buildArgs': "--rpath --jemalloc --gcc6 --rpmDistro SUSE13", 'cluster': true,  'LOCALFS': '/mnt/workspace/tmp/', 'FS': '/mnt/data/fileserver/', 'reliable': true, 'BUILD': '', 'CBUILD':'', 'SYMSRV':'', 'testArgs': ''],
  [ 'buildType': 'docker', 'testType': 'docker', 'name': 'debianjessie',        'packageFormat': 'DEB',    'OS': "Linux",   'buildArgs': "--rpath --jemalloc", 'cluster': true,  'LOCALFS': '/mnt/workspace/tmp/', 'FS': '/mnt/data/fileserver/', 'reliable': true, 'BUILD': '', 'CBUILD':'', 'SYMSRV':'', 'testArgs': ''],
  [ 'buildType': 'docker', 'testType': 'docker', 'name': 'ubuntutwelveofour',   'packageFormat': 'DEB',    'OS': "Linux",   'buildArgs': "--rpath --jemalloc", 'cluster': true,  'LOCALFS': '/mnt/workspace/tmp/', 'FS': '/mnt/data/fileserver/', 'reliable': false, 'BUILD': '', 'CBUILD':'', 'SYMSRV':'', 'testArgs': ''],
  [ 'buildType': 'docker', 'testType': 'docker', 'name': 'ubuntufourteenofour', 'packageFormat': 'DEB',    'OS': "Linux",   'buildArgs': "--rpath --jemalloc", 'cluster': true,  'LOCALFS': '/mnt/workspace/tmp/', 'FS': '/mnt/data/fileserver/', 'reliable': true, 'BUILD': '', 'CBUILD':'', 'SYMSRV':'', 'testArgs': ''],
  [ 'buildType': 'docker', 'testType': 'docker', 'name': 'ubuntusixteenofour',  'packageFormat': 'DEB',    'OS': "Linux",   'buildArgs': "--rpath --jemalloc --snap", 'cluster': true,  'LOCALFS': '/mnt/workspace/tmp/', 'FS': '/mnt/data/fileserver/', 'reliable': true, 'BUILD': '', 'CBUILD':'', 'SYMSRV':'', 'testArgs': ''],

  //  [ 'buildType': 'docker', 'testType': 'docker', 'name': 'ubuntusixteenarmhfxc', 'packageFormat': 'DEB',    'OS': "Linux",   'buildArgs': "--xcArm /usr/bin/arm-linux-gnueabihf --noopt", 'cluster': true,  'LOCALFS': '/mnt/workspace/tmp/', 'FS': '/mnt/data/fileserver/', 'reliable': true, 'BUILD': '', 'CBUILD':'', 'SYMSRV':''],
  // compiler to old ;-)  [ 'buildType': 'docker', 'testType': 'docker', 'name': 'ubuntufourteenarmhfxc', 'packageFormat': 'DEB',    'OS': "Linux",   'buildArgs': "--xcArm /usr/bin/arm-linux-gnueabihf --noopt", 'cluster': true,  'LOCALFS': '/mnt/workspace/tmp/', 'FS': '/mnt/data/fileserver/', 'reliable': true, 'BUILD': '', 'CBUILD':'', 'SYMSRV':''],
  // [ 'buildType': 'docker', 'testType': 'docker', 'name': 'debianjessiearmhfxc', 'packageFormat': 'DEB',    'OS': "Linux",   'buildArgs': "--xcArm /usr/bin/arm-linux-gnueabihf --noopt", 'cluster': true,  'LOCALFS': '/mnt/workspace/tmp/', 'FS': '/mnt/data/fileserver/', 'reliable': true, 'BUILD': '', 'CBUILD':'', 'SYMSRV':'', 'testArgs': ''],

  [ 'buildType': 'native', 'testType': 'native', 'name': 'macos',               'packageFormat': 'Bundle', 'OS': "Darwin",  'buildArgs': "--clang --staticOpenSSL",    'cluster': false, 'LOCALFS': '/Users/jenkins/mnt/workspace/tmp/', 'FS': '/Users/jenkins/net/fileserver/', 'reliable': true, 'BUILD': '', 'CBUILD':'', 'SYMSRV':'', 'testArgs': ''],
  [ 'buildType': 'native', 'testType': 'native', 'name': 'windows',             'packageFormat': 'NSIS',   'OS': "CYGWIN_NT-10.0", 'buildArgs': "--msvc",     'cluster': false, 'LOCALFS': 'c:/mnt/workspace/tmp/', 'FS': '/var/tmp/r', 'reliable': true, 'BUILD': "../../${testPathPrefix}_", 'CBUILD': "../../${testPathPrefix}c_", 'SYMSRV': '/cygdrive/e/symsrv/', 'testArgs': "--ruby c:/tools/ruby23/bin/ruby.exe --rspec c:/tools/ruby23/bin/rspec"]
]

if (preferBuilder.size() > 0) {
  found=false
  for (int c  = 0; c < CONTAINERS.size(); c++) {
    if (CONTAINERS[c]['name'] == preferBuilder) {
      print("prefering: ${CONTAINERS[c]}")
      found=true
      DOCKER_CONTAINER = CONTAINERS[c]
      RELEASE_OUT_DIR = DOCKER_CONTAINER['FS']
      LOCAL_TAR_DIR = DOCKER_CONTAINER['LOCALFS']
      BUILD_DIR = DOCKER_CONTAINER['BUILD']
      TEST_ARGS = DOCKER_CONTAINER['testArgs']
    }
  }
  if (!found) {
    throw new Exception("didn't find the builder '${preferBuilder}' you specified!")
  }
} else {
  for (int c  = 0; c < CONTAINERS.size(); c++) {
    if (CONTAINERS[c]['buildType'] == 'docker') {
      DOCKER_CONTAINER = CONTAINERS[c]
      RELEASE_OUT_DIR = DOCKER_CONTAINER['FS']
      LOCAL_TAR_DIR = DOCKER_CONTAINER['LOCALFS']
      BUILD_DIR = DOCKER_CONTAINER['BUILD']
      TEST_ARGS = DOCKER_CONTAINER['testArgs']
    }
  }
}

OS = DOCKER_CONTAINER['OS']
DOCKER_CONTAINER['cluster'] = (RUN_CLUSTER_TESTS == "true")

lastKnownGoodGitFile="${RELEASE_OUT_DIR}/${env.JOB_NAME}.githash"

DIST_FILE = "${RELEASE_OUT_DIR}/arangodb-${OS}.tar.gz".replace("/cygdrive/c", "c:")
echo(DIST_FILE)

////////////////////////////////////////////////////////////////////////////////
// Test tarball

def getReleaseOutDir(String enterpriseUrl, String jobname) {
  if (enterpriseUrl.size() > 10) {
    outDir = "${RELEASE_OUT_DIR}/EP/${jobname}"
  } else {
    outDir = "${RELEASE_OUT_DIR}/CO/${jobname}"
  }
  return outDir
}

def setDirectories(where, String localTarDir, String OS, String jobName, String MD5SUM, String distFile, String testRunName, String unitTests, String cmdLineArgs, String releaseOutDir, String EPDIR) {
  localTarball="${localTarDir}/arangodb-${OS}.tar.gz"
  where['localTarDir'] = localTarDir
  where['localTarball'] = localTarball
  where['localWSDir']="${localTarDir}/${jobName}"
  where['localExtractDir']="${where['localWSDir']}/x${EPDIR}/"
  where['MD5SUM'] = MD5SUM
  where['distFile'] = distFile

  where['testRunName'] = testRunName
  where['unitTests'] = unitTests
  where['cmdLineArgs'] = cmdLineArgs
  where['releaseOutDir'] = releaseOutDir
}

def copyExtractTarBall (where, String buildHost, String testWorkingDirectory) {
  print("${where['testRunName']}: copyExtractTarBall\n")
  extract_tarball = where['localTarball'].replace("c:", "/cygdrive/c")

  CMD = """
if test ! -d ${where['localTarDir']}; then
        mkdir -p ${where['localTarDir']}
fi
if test ! -d ${where['localWSDir']}; then
        mkdir -p ${where['localWSDir']}
fi
if test ! -d ${where['localExtractDir']}; then
        mkdir -p ${where['localExtractDir']}
fi
if test ! -d ${where['releaseOutDir']}; then
        mkdir -p ${where['releaseOutDir']}
fi
python /usr/bin/copyFileLockedIfNewer.py ${where['MD5SUM']} ${where['distFile']} ${where['localWSDir']} ${where['localTarball']} '${where['testRunName']}_${buildHost}' 'rm -rf ${where['localExtractDir']}; mkdir ${where['localExtractDir']}; cd ${where['localExtractDir']}; tar -xzf ${extract_tarball}'
"""

  if (VERBOSE) {
    print CMD
  }
  sh CMD
}

def setupTestArea(where, testWorkingDirectory) {
  if (VERBOSE) {
    print("${where['testRunName']}: setupTestArea\n")
    print(where)
  }

  def createDirectory = "mkdir -p ${testWorkingDirectory}/out/ "
  def cleanOutFiles = "rm -rf ${testWorkingDirectory}/out/*"
  def removeOldSymlinks = "cd ${testWorkingDirectory}/; find . -type l -exec rm -f {} \\;;"
  def createNewSymlinks = "ln -s ${where['localExtractDir']}/* ${testWorkingDirectory}/ || true"
  if (VERBOSE) {
    sh "cat /mnt/workspace/issue"
    print(cleanOutFiles)
    print(createDirectory)
    print(cleanOutFiles)
    print(removeOldSymlinks)
    print(createNewSymlinks)
  }
  sh cleanOutFiles
  sh createDirectory
  sh cleanOutFiles
  sh removeOldSymlinks
  sh createNewSymlinks
}

def runTests(where, testWorkingDirectory) {
  def EXTREME_VERBOSITY=""
  if (VERBOSE) {
    print("${where['testRunName']}: runTests")
    //EXTREME_VERBOSITY="--extremeVerbosity true"
  }

  def TESTWD = "${testWorkingDirectory}/out".replace("/cygdrive/c", "c:")
  def cdTestWD = ""
  if (OS == "CYGWIN_NT-10.0") {
    cdTestWD = "cd ${where['localExtractDir']}"
  }

  def RCFile = "${testWorkingDirectory}/out/rc"
  def SHELL = env.SHELL;
  if (SHELL == "") {
    SHELL="/bin/bash"
  }
  def EXECUTE_TEST="""pwd;
         ulimit -c unlimited
         cat /mnt/workspace/issue
         ${cdTestWD}
         export TMPDIR=${testWorkingDirectory}/out/tmp
         export SHELL=${SHELL}
         mkdir -p \${TMPDIR}
         echo 0 > ${RCFile}
         ls -l
         bash -x ${where['localExtractDir']}/scripts/unittest ${where['unitTests']} \
                --skipNondeterministic true \
                --skipTimeCritical true \
                --testOutput ${TESTWD} \
                ${EXTREME_VERBOSITY} \
                ${TEST_ARGS} \
                ${where['cmdLineArgs']} || \
         echo \$? > ${RCFile}"""

  if (VERBOSE) {
    echo "${where['testRunName']}: ${EXECUTE_TEST}"
  }
  wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'XTerm']) {
    sh EXECUTE_TEST
  }
  def shellRC = sh(returnStdout: true, script: "cat ${RCFile}").trim()
  if (shellRC != "0") {
    failures = "${failures};test ${where['testRunName']} exited with ${shellRC}"
  }
  if (VERBOSE) {
    echo "${where['testRunName']}: recording results [ ${TESTWD}/*.xml ]:"
    sh "ls -l out/UNITTEST_RESULT_*.xml"
  }

  junit keepLongStdio: true, testResults: "out/*.xml"
  print("The currentBuild.result is: ${currentBuild.result}")
  def crashy = readFile("${TESTWD}/UNITTEST_RESULT_CRASHED.json")
  def testFailuresFile = "${TESTWD}/testfailures.txt"
  def failureOutput = readFile(testFailuresFile)
  def res = 'SUCCESS'
  if (failureOutput.size() > 5) {
    echo "switching to UNSTABLE!"
    sh "cp ${testFailuresFile} ${where['releaseOutDir']}/results/${where['testRunName']}.txt"
    return 'UNSTABLE'
  }
  else {
    def executiveSummary = readFile("${TESTWD}/UNITTEST_RESULT_EXECUTIVE_SUMMARY.json").trim()
    echo "executiveSummary: ${executiveSummary} - ${crashy}"

    if (crashy == "true") {
      res = currentBuild.result = 'FAILURE'
    }
  }
  return res
}

def runThisTest(which, buildEnvironment)
{
  def rc=false
  print('runThisTest')
  def testWorkingDirectory;
  def where = testParams[which]
  if (buildEnvironment['testType'] == 'docker') {
    print("in")
    node('docker') {
      sh 'pwd > workspace.loc'
      def WORKSPACE = readFile('workspace.loc').trim()
      testWorkingDirectory="${WORKSPACE}/${where['testRunName']}"
      if (VERBOSE) {
        print("hello ${which}: ${where['testRunName']} ${where} RUNNING in ${WORKSPACE}")
      }
      dir("${where['testRunName']}") {
        if (VERBOSE) {
          echo "Hi, I'm [${where['testRunName']}] - ${where['unitTests']}"
        }
        docker.withRegistry(REGISTRY_URL, '') {
          def myRunImage = docker.image("${buildEnvironment['name']}/run")
          myRunImage.pull()
          docker.image(myRunImage.imageName()).inside("--volume /mnt/data/fileserver:${RELEASE_OUT_DIR}:rw --volume /jenkins:/mnt/:rw --volume /var/lib/systemd/coredump:/var/lib/systemd/coredump:rw") {
            def buildHost=sh(returnStdout: true, script: "cat /mnt/workspace/issue").trim()
            buildHost = buildHost[32..35]
            if (VERBOSE) {
              sh "cat /etc/issue"
              sh "pwd"
              echo "${env} ${buildHost}"
            }
            // GO!
            copyExtractTarBall(where, buildHost, testWorkingDirectory)
            setupTestArea(where, testWorkingDirectory)
            rc = runTests(where, testWorkingDirectory)
          }
        }
      }
    }
  }
  else {
    print("else")
    print(buildEnvironment)
    node(buildEnvironment['name']){
      print("on node")
      sh 'pwd > workspace.loc'
      def WORKSPACE = readFile('workspace.loc').trim()
      print("setting workspace")
      testWorkingDirectory="${WORKSPACE}/${where['testRunName']}"
      print("done")
      if (VERBOSE) {
        print("hello ${which}: ${where['testRunName']} ${where} RUNNING in ${WORKSPACE}")
      }
      dir("${where['testRunName']}") {
        print("on directory")
        if (VERBOSE) {
          echo "Hi, I'm [${where['testRunName']}] - ${where['unitTests']}"
        }
        def buildHost=buildEnvironment['name']
        // GO!
        copyExtractTarBall(where, buildHost, testWorkingDirectory)
        setupTestArea(where, testWorkingDirectory)
        rc = runTests(where, testWorkingDirectory)
      }
    }
  }
  /*
  if (!rc) {
    new Exception("test failed.")
  }
  */
}

////////////////////////////////////////////////////////////////////////////////
// Build source
def compileSource(buildEnv, Boolean buildUnittestTarball, String enterpriseUrl, String outDir, String envName, Boolean Reliable) {
  try {
    // sh "cmake --version"
    def EP=""
    def XEP=""
    if (enterpriseUrl.size() > 10) {
      EP="--enterprise ${ENTERPRISE_URL}"
      XEP="EP"
    }
    if (!buildUnittestTarball) {
      outDir = getReleaseOutDir(enterpriseUrl, envName)
    }
    print(buildEnv)
    def buildDir = ""
    if (buildEnv['BUILD'].size() == 0) {
      buildDir = "build-${XEP}package-${buildEnv['name']}"
    }
    else {
      buildDir = "${buildEnv['BUILD']}${XEP}"
    }
    def cBuildDir = ""
    if (buildEnv['CBUILD'].size() != 0) {
      cBuildDir = "--clientBuildDir ${buildEnv['CBUILD']}${XEP}"
    }

    def buildMode = "standard"
    if (MAINTAINERMODE == "true") {
      buildMode = "maintainer"
    }

    def BUILDSCRIPT = "./Installation/Jenkins/build.sh ${buildMode} --parallel ${PARALLEL_BUILD} --buildDir ${buildDir} ${cBuildDir} ${EP} --targetDir ${outDir} ${buildEnv['buildArgs']}"

    if (! buildUnittestTarball) {
      BUILDSCRIPT="${BUILDSCRIPT} --package ${buildEnv['packageFormat']} --downloadStarter"
    }
    if (buildEnv['SYMSRV'].size() != 0) {
      BUILDSCRIPT="${BUILDSCRIPT} --symsrv ${buildEnv['SYMSRV']} "
    }
    if (CLEAN_BUILDENV == "true") {
      BUILDSCRIPT="rm -rf ${buildDir} ; ${BUILDSCRIPT}"
    }
    else if (CLEAN_CMAKE_STATE == "true") {
      BUILDSCRIPT="rm -rf ${buildDir}/CMakeFiles ${buildDir}/CMakeCache.txt ${buildDir}/CMakeCPackOptions.cmake ${buildDir}/cmake_install.cmake ${buildDir}/CPackConfig.cmake ${buildDir}/CPackSourceConfig.cmake ;${BUILDSCRIPT}"
    }
    if (!Reliable && (SKIP_BUILD != "true")) {
      BUILDSCRIPT="""nohup bash -c "${BUILDSCRIPT}" > nohup.out 2>&1 & PID=\$!; echo \$PID > pid; tail -f nohup.out & wait \$PID; kill %2 ||true"""
      try {
        if (VERBOSE) {
          print(BUILDSCRIPT)
        }
        sh BUILDSCRIPT
      }
      catch (err) {
        RUNNING_PID=readFile("pid").trim()
        def stillRunning=true
        while (stillRunning) {
          def processStat=""
          try{
            scripT="cat /proc/${RUNNING_PID}/stat 2>/dev/null"
            echo "script: ${scripT}"
            processStat = sh(returnStdout: true, script: scripT).trim()
          }
          catch (x){}
          stillRunning=(processStat != "")
          sleep 5
        }
        sh "tail -n 100 nohup.out"
      }
    }
    else {
      // we expect this docker to run stable, so we don't fuck aroundwith nohup
      if (VERBOSE) {
        print(BUILDSCRIPT)
      }
      if (SKIP_BUILD != "true") {
        sh BUILDSCRIPT
      }
    }
    if (buildUnittestTarball) {
      sh "mkdir -p ${RELEASE_OUT_DIR}"

      BUILT_FILE = "${outDir}/arangodb-${OS}.tar.gz".replace("/cygdrive/c", "c:")
      DIST_FILE = "${RELEASE_OUT_DIR}/arangodb-${OS}.tar.gz".replace("/cygdrive/c", "c:")
      echo(DIST_FILE)
      echo(BUILT_FILE)
      MD5SUM = readFile("${BUILT_FILE}.md5").trim()

      if (VERBOSE) {
        echo "copying result files: '${MD5SUM}' '${BUILT_FILE}' '${DIST_FILE}.lock' '${DIST_FILE}'"
      }

      sh "python /usr/bin/copyFileLockedIfNewer.py ${MD5SUM} ${BUILT_FILE} ${DIST_FILE}.lock ${DIST_FILE} ${env.JOB_NAME}"
    }
    else {
      // TODO: release?
    }
    if (VERBOSE) {
      sh "ls -l ${RELEASE_OUT_DIR}"
    }
  } catch (err) {
    stage('Send Notification for failed build' ) {
      gitCommitter = sh(returnStdout: true, script: 'git --no-pager show -s --format="%ae"')

      mail (to: gitCommitter,
            subject: "Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) 'building ArangoDB' failed to compile.", 
            body: err.getMessage());
      currentBuild.result = 'FAILURE'
      throw(err)
    }
  }
}

def setupEnvCompileSource(buildEnvironment, Boolean buildUnittestTarball, String enterpriseUrl, String EPDIR, Boolean Reliable){
  def outDir = ""
  print(buildEnvironment)
  if (buildEnvironment['buildType'] == 'docker') {
    node(DOCKER_HOST) {
      sh "set"
      docker.withRegistry(REGISTRY_URL, '') {
        def myBuildImage = docker.image("${buildEnvironment['name']}/build")
        myBuildImage.pull()
        echo "hello before docker ${RELEASE_OUT_DIR}"
        docker.image(myBuildImage.imageName()).inside("""\
 --volume /mnt/data/fileserver:${RELEASE_OUT_DIR}:rw\
 --volume /jenkins:/mnt/:rw \
""") {
          //           docker.image(myBuildImage.imageName()).withRun("""\
          //  -u 1000:1000 \
          // --volume /mnt/data/fileserver:${RELEASE_OUT_DIR}:rw \
          // --volume /jenkins:/mnt/:rw \
          // --volume /var/lib/jenkins/workspace/ArangoDB_Release:/var/lib/jenkins/workspace/ArangoDB_Release:rw \
          // """) { c->
          echo "hello from docker"
          if (VERBOSE && Reliable) {
            sh "mount"
            sh "pwd"
            sh "cat /etc/issue /mnt/workspace/issue /etc/passwd"
            
          }

          sh 'pwd > workspace.loc'
          WORKSPACE = readFile('workspace.loc').trim()
          outDir = "${WORKSPACE}/out${EPDIR}"
          compileSource(buildEnvironment, buildUnittestTarball, enterpriseUrl, outDir, buildEnvironment['name'], Reliable)
        }
      }
    }
  }
  else {
    print("building native")
    node(buildEnvironment['name']){
      print "else:"
      echo "building on ${buildEnvironment['name']}"
      sh 'pwd > workspace.loc'
      WORKSPACE = readFile('workspace.loc').trim()
      outDir = "${WORKSPACE}/out${EPDIR}"
      compileSource(buildEnvironment, buildUnittestTarball, enterpriseUrl, outDir, buildEnvironment['name'], Reliable)
    }
  }
}

def CloneSource(inDocker){
      if (VERBOSE) {
        sh "pwd"
        if (inDocker) {
          sh "cat /etc/issue /jenkins/workspace/issue"
        }
        else {
          sh "uname -a"
        }
      }

      sh "rm -f 3rdParty/rocksdb/rocksdb/util/build_version.cc"
      checkout([$class: 'GitSCM',
                branches: [[name: "${GITTAG}"]],
                /*
                doGenerateSubmoduleConfigurations: false,
                extensions: [[$class: 'SubmoduleOption',
                              disableSubmodules: false,
                              parentCredentials: false,
                              recursiveSubmodules: true,
                              reference: '',
                              trackingSubmodules: false]],
                submoduleCfg: [],
                */
                extensions: [
                  [$class: 'CheckoutOption', timeout: 20],
                  [$class: 'CloneOption', timeout: 20]
                ],
                userRemoteConfigs:
                [[url: 'https://github.com/arangodb/arangodb.git']]])

      // follow deletion of upstream tags:
      sh "git fetch --prune origin +refs/tags/*:refs/tags/*"
      currentGitRev = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
      if (fileExists(lastKnownGoodGitFile)) {
        lastKnownGitRev=readFile(lastKnownGoodGitFile)
      }
      currentGitRev = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
      print("GIT_AUTHOR_EMAIL: ${env} ${currentGitRev}")
}

stage("cloning source") {
  print(DOCKER_CONTAINER)
  if (DOCKER_CONTAINER['buildType'] == 'docker') {
    node(DOCKER_HOST) {
      CloneSource(true)
    }
  }
  else {
    node(DOCKER_CONTAINER['name']) {
      CloneSource(false)
    }
  }
}

stage("building ArangoDB") {
  EPDIR=""
  if (ENTERPRISE_URL != "") {
    EPDIR="EP"
  }
  try {
    print(DOCKER_CONTAINER)
    setupEnvCompileSource(DOCKER_CONTAINER, true, ENTERPRISE_URL, EPDIR, DOCKER_CONTAINER['reliable'])
  } catch (err) {
    stage('Send Notification for build' ) {
      mail (to: ADMIN_ACCOUNT,
            subject: "Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) 'building ArangoDB' has had a FATAL error.", 
            body: err.getMessage());
      currentBuild.result = 'FAILURE'
    }
    throw(err)
  }
}

stage("running unittest") {
  try {
    def testCaseSets = [:]
    if (DOCKER_CONTAINER['cluster']) {
      testCaseSets = [
        //  ["fail", 'fail', ""],
        //    ["fail", 'fail', ""],
        ['catch', 'catch', ""],
        ['http_server', 'http_server', "",
         "--cluster true --testBuckets 4/1 ",
         "--cluster true --testBuckets 4/2 ",
         "--cluster true --testBuckets 4/3 ",
         "--cluster true --testBuckets 4/4 "],
        ["shell_client", 'shell_client', "",
         "--cluster true "],
        ["shell_server_aql", 'shell_server_aql', "",
         "--cluster true --testBuckets 4/1 ",
         "--cluster true --testBuckets 4/2 ",
         "--cluster true --testBuckets 4/3 ",
         "--cluster true --testBuckets 4/4 "],
        ["dump_import", 'dump.importing', "", "--cluster true"],
        ["shell_server", 'shell_server', "",
         "--cluster true "],
        // ['ssl_server', 'ssl_server', ""], // FC: don''t need this with clusters.
        ["overal", 'config.upgrade.authentication.authentication_parameters.arangobench', ""],
        ["arangosh", 'arangosh', ""],
      ]
    } else {
      testCaseSets = [/*
        ["fail", 'fail', ""],
        ["overal", 'config.authentication', ""],
        ["fail", 'fail', ""],/*///
        ['catch', 'catch', ""],
        ['http_server', 'http_server', ""],
        ["shell_client", 'shell_client', ""],
        ["shell_server_aql", 'shell_server_aql', ""],
        ["dump_import", 'dump.importing', ""],
        ["shell_server", 'shell_server', ""],
        ['ssl_server', 'ssl_server', ""],
        ["overal", 'config.upgrade.authentication.authentication_parameters.arangobench', ""],
        ["arangosh", 'arangosh', ""],
        //*/
      ]
    }
    print("getting keyset\n")
    def releaseOutDir = getReleaseOutDir(ENTERPRISE_URL, env.JOB_NAME)
    if (DOCKER_CONTAINER['buildType'] == 'docker') {
      node('docker') {
        sh "mkdir -p ${releaseOutDir}/results/ ; rm -f ${releaseOutDir}/results/*;"
      }
    } else {
      node(DOCKER_CONTAINER['name']) {
        sh "mkdir -p ${releaseOutDir}/results/ ; rm -f ${releaseOutDir}/results/*;"
      }
    }
    m = testCaseSets.size()
    int n = 0;
    for (int i = 0; i < m; i++) {
      def unitTestSet = testCaseSets.getAt(i);
      o = unitTestSet.size()
      def unitTests = unitTestSet.getAt(1);
      def shortName = unitTestSet.getAt(0);
      for (int j = 2; j < o; j ++ ) {
        def cmdLineArgs = unitTestSet.getAt(j)
        echo " ${shortName} ${cmdLineArgs} -  ${j}"
        testRunName = "${shortName}_${j}_${n}"
        parallelJobNames[n]=testRunName
        testParams[testRunName] = [:]
        EPDIR = ""
        if (ENTERPRISE_URL != "") {
          EPDIR = "EP"
        }
        setDirectories(testParams[testRunName], LOCAL_TAR_DIR, DOCKER_CONTAINER['OS'], env.JOB_NAME, MD5SUM, DIST_FILE, testRunName, unitTests, cmdLineArgs, releaseOutDir, EPDIR)
        n += 1
      }
    }
    print("setting up paralel branches")
    for (int i = 0; i < parallelJobNames.size(); i++) {
      def thisTestRunName = parallelJobNames[i]
      branches[thisTestRunName] = {
        runThisTest(thisTestRunName, DOCKER_CONTAINER)
      }
    }
    echo branches.toString();

    parallel branches
    print("The currentBuild.result is now after the parallel: ${currentBuild.result}")

  } catch (err) {
    stage('Send Notification unittest') {
      mail (to: ADMIN_ACCOUNT,
            subject: "Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) 'running unittest' has had a FATAL error.", 
            body: "error message: " + err.getMessage());
      currentBuild.result = 'FAILURE'
    }
    throw(err)
  }
}

stage("generating test report") {
  if (DOCKER_CONTAINER['buildType'] == 'docker') {
    nodeName = 'docker'
  } else {
    nodeName = DOCKER_CONTAINER['name']
  }
  node(nodeName) {
    def releaseOutDir = getReleaseOutDir(ENTERPRISE_URL, env.JOB_NAME)
    
    def failures = failures + "\n" +  sh(returnStdout: true, script: "cat ${releaseOutDir}/results/* || echo ''").trim()

    if (failures.size() > 5) {

      print(failures)

      def gitRange = ""
      if (lastKnownGitRev.size() > 1) {
        gitRange = "${lastKnownGitRev}.."
      }
      gitRange = "${gitRange}${currentGitRev}"
      if (VERBOSE) {
        print(gitRange)
      }
      def gitcmd = 'git --no-pager show -s --format="%ae>" ${gitRange} |sort -u |sed -e :a -e \'$!N;s/\\n//;ta\' -e \'s;>;, ;g\' -e \'s;, $;;\''
      if (VERBOSE) {
        print(gitcmd)
      }
      gitCommitters = sh(returnStdout: true, script: gitcmd)
      if (VERBOSE) {
        echo gitCommitters
      }
      def subject = ""
      if (fatalError) {
        subject = "Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) has failed MISERABLY! "
      }
      else {
        subject = "Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) has failed"
      }

      if (REPORT_TO == "slack") {
        // Accusing: ${gitCommitters} \n
        slackMsg = """Branch '${GITTAG}' on '${preferBuilder}' failed: (${env.BUILD_URL}) \n  ```${failures}```"""
        slackSend channel: '#status-dev', color: '#FF0000', message: slackMsg

      }
      else if (REPORT_TO == "mail") {
        print("sending messages to ${gitCommitters}")
        mail (to: gitCommitters,
              subject: subject,
              body: "the failed testcases gave this output: ${failures}\nPlease go to ${env.BUILD_URL}.");
      }
      else { // report to upstream process via artifact
        msg = """${GITTAG} on ${preferBuilder} failed (${env.BUILD_URL}) \n Accusing: ${gitCommitters} \n ${failures}"""
        jstr = new JsonBuilder(['status':false, 'messge': msg]).toPrettyString()
        writeFile file: REPORT_TO, text: jstr
        archive REPORT_TO
      }
    }
    else {
      sh "echo ${currentGitRev} > ${lastKnownGoodGitFile}";

      if (REPORT_TO == "slack") {
	// no success messages for now. slackSend channel: '#status-dev', color: '#00FF00', message: "${GITTAG} on ${preferBuilder} succeeded (${env.BUILD_URL}) OK"
      }
      else if (REPORT_TO == "mail") {
      }
      else { // report to upstream process via artifact
        jstr = new JsonBuilder(['status':false, 'messge': "success"]).toPrettyString()
        writeFile file: REPORT_TO, text: jstr
      }
    }
  }
}
